### ISSUE TITLE
Некорректная обработка скобок

### ISSUE THREAD

**Issue by finomen** [lytr777/C#3]
./Calc 
( 2 + 2 ) ) ) ) )
4

**Comment by lytr777** [comment]
Добавлена функция bracket_balance

**Comment by finomen** [comment]
(2+2) - Segmentation fault

2015-05-12 19:17 GMT+03:00 lytr777 <notifications@github.com>:

> Добавлена функция bracket_balance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lytr777/C/issues/3#issuecomment-101336472>.
>



-- 
Best wishes.
Nikolay Filchenko
