### ISSUE TITLE
Второе задание явно не соответсвует тому, что требовалось

### ISSUE THREAD

**Issue by finomen** [lytr777/C#4]
Интерфейс пользователя
Ввод размера стартовой позиции
Ввод количества заселенных клеток для первого шага
Ввод количесва шагов симуляции
Выыод статистики
Количество заселенных клеток каждые 10 шагов
Среднее соотношение родившихся/умерших за каждые 10 шагов
Прирост популяции по окончании симуляции
Номер шага, после которого размер популяции не менялся (если такой будет)

**Comment by lytr777** [comment]
Обновил

**Comment by finomen** [comment]
finomen@finomen ~/cpp_2014/39/Life $ ./Life
▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒ : 96
▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒/▒▒▒▒▒▒▒ : 1.31507

▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒ : 81
▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒/▒▒▒▒▒▒▒ : 0.778846

▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒ : 48
▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒/▒▒▒▒▒▒▒ : 0.786885

▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ : -13
▒▒▒▒▒▒▒▒▒ ▒▒ ▒▒▒▒▒▒▒▒▒▒ ▒ 28 ▒▒▒▒
▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒▒ ▒▒ 37 ▒▒▒▒ ▒▒ ▒▒ ▒▒▒▒▒▒▒▒▒▒▒▒

Нечитаемо. И как генерить случайное поле?


2015-05-06 23:05 GMT+04:00 lytr777 <notifications@github.com>:

> Обновил
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lytr777/C/issues/4#issuecomment-99576406>.
>



-- 
Best wishes.
Nikolay Filchenko

**Comment by lytr777** [comment]
Еще раз обновил

**Comment by lytr777** [comment]
И пожалуйста посмотрите 3 задание.
